"""empty message

Revision ID: 1f3ff849a9d1
Revises: 9960d5ba17b7
Create Date: 2023-02-27 23:47:11.560922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f3ff849a9d1'
down_revision = '9960d5ba17b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_email_captcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('captcha', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_email_captcha')
    # ### end Alembic commands ###
